config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, :controllers => { :confirmations => "confirmations", registrations: 'registrations'  }
  root 'v2/dashboards#index'
  get :start, to: 'dashboards#start'

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  mount_griddler
  resources :plans, only: [:index] do
    collection do
      get 'upgrade'
    end
  end
  resources :teams, except: [:index] do
    member do
      post 'add_users'
      get 'approve_request'
      get 'activity'
      post 'role_change'
      get 'members'
      get 'resend_invitation'
      post 'remove_user'
      get 'disable'
    end
  end

  get '/slack/callback', to: 'slack#callback'
  get '/github/callback', to: 'github#callback'

  resources :github_hooks, only: [:new, :create, :edit, :update] do
    collection do
      post '/teams/:team_id/payload', to: 'github_hooks#payload'
    end
  end

  resource :user, only: [:show, :edit, :update]

  resources :posts, only: [:index, :new, :create, :edit, :update] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end

  resources :instant_posts do
    collection do
      get 'instant_updates'
      post 'save_updates'
    end
  end
  resources :reports, only: [:index]

  # Super Admin dashboard
  namespace :admin, path: 'captains', as: 'captains' do
    resource :dashboard, only: [], path: "deck", as: 'deck' do
      member do
        get 'full'
        get 'today'
      end
    end
  end

  namespace :v2 do
    resources :teams, except: [:index] do
      member do
        post 'add_users'
        get 'approve_request'
        get 'activity'
        post 'role_change'
        get 'members'
        get 'resend_invitation'
        post 'remove_user'
        get 'disable'
      end
      resources :tasks do
        member do
          put 'complete'
          put 'reset'
          put 'blocker'
          put 'change_assignee'
        end
        collection do
          get 'prepare_tasks'
          post 'add_my_task'
          get 'user_task'
          get 'my_task'
          get 'team_task'
        end
      end

      resources :tags, only: [:show] do
        collection do
          get 'tasks_list'
        end
      end
    end

    resources :tasks, only: [:index] do
      collection do
        get 'report'
        get 'find_users'
      end
    end
    get '/slack/callback', to: 'slack#callback'
    get '/github/callback', to: 'github#callback'

    resources :github_hooks, only: [:new, :create, :edit, :update] do
      collection do
        post '/teams/:team_id/payload', to: 'github_hooks#payload'
      end
    end

    resources :dashboards, only: [:index]
  end

  resources :orders, only: [:new, :create] do
    member do
      get 'success'
      get 'error'
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @team  = Team.new
    authorize @team
    @team.build_team_setting
  end

  def index
    @teams = current_user.teams
  end

  def create
    @team = Team.new(team_params)
    params[:team][:team_setting_attributes][:days] ||= []
    if @team.save
      @team.users << current_user
      current_user.approve_team(@team)
      flash[:notice] = "Team created successfully"
      redirect_to @team
    else
      render :new
    end
  end

  def show
    @team = Team.includes(:users).find(params[:id])
    authorize @team
  end

  def edit
    @team = Team.find(params[:id])
    session[:team_id] = @team.id
    respond_to do |format|
      format.js
    end
  end

  def update
    @team = Team.find(params[:id])
    params[:team][:team_setting_attributes][:days] ||= []
    if @team.update(edit_params)
      redirect_to @team
    else
      render :edit
    end
  end

  def activity
    @team = Team.find(params[:id])
    if current_user.plan.data_retention?
      @team_posts = Post.joins(:user).includes(:user)
        .where(team_id: params[:id])
        .where("received_date >= '#{(Post::DAYS_LIMIT).days.ago}'")
    else
      @team_posts = Post.joins(:user).includes(:user)
        .where(team_id: params[:id])
    end
    @posts = @team_posts.order("received_date DESC, users.name ASC").group_by(&:date)
    @commits = ExtActivity.joins(:user).where(team_id: params[:id]).order("event_time DESC, users.name ASC").group_by(&:date)
    dates = (@posts.keys + @commits.keys).sort!.uniq.reverse
    @activity= {}
    dates.each do |date|
      @activity[date] = [@posts[date], @commits[date]].compact.flatten
    end
    respond_to do |format|
      format.js
    end
  end

  def members
    @team = Team.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def approve_request
    team = Team.find(params[:id])
    current_user.approve_team(team)
    redirect_to team_path(team)
  end

  def add_users
    authorize team
    email_list = params[:email].delete_if { |k, v| v.empty? }
    name_list = params[:name].delete_if { |k, v| v.empty? }
    ob_list = params[:observer].delete_if { |k, v| v.empty? } if params[:observer]

    if email_list.present? && name_list.present?
      email_list.each do |key,email|
        user = User.where(email: email).first
        if !user.present?
          user = User.new(email: email, name: name_list[key], status: false)
          user.save!(validate: false)
        end
        if !team.users.include?user
          role = 'observer' if ob_list && ob_list[key] == "1"
          user.allotments.create!(team_id: team.id, role: role || 'member')
          user.send_invite(team, current_user)
          flash[:notice] = "Team members added successfully"
        else
          flash[:notice] = "User is already in the team."
        end
      end
    end
    redirect_to team
  end

  def role_change
    checked = params[:checked]
    allotment = team.allotment(user)
    if checked == "false"
      role_observer = allotment.update(role: "member")
    else
      role_member = allotment.update(role: "observer")
    end
    redirect_to members_team_path(team)
  end

  def resend_invitation
    authorize team, :update?
    if (!team.approved?(user)) && (team.users.include?(user))
      user.resend_invite(team, current_user)
      redirect_to members_team_path(team), notice: 'Invitation sent'
    else
      redirect_to members_team_path(team), notice: 'User is already in the team.'
    end
  end

  def disable
    team.destroy
    redirect_to root_path, notice: 'Team Deleted Successfully'
  end

  def remove_user
    authorize team, :update?
    authorize user
    remove_from_team = team.allotment(user).destroy
    redirect_to members_team_path(team)
  end

  private

  def team
    Team.find(params[:id])
  end

  def user
    User.find(params[:user_id])
  end

  def team_params
    params.require(:team).permit(:name, :uid, team_setting_attributes: [:question_email_at, :digest_email_at, :timezone, :photo, days: []]).merge(created_by: current_user.id)
  end

  def edit_params
    params.require(:team).permit(:name, :uid, team_setting_attributes: [:id, :question_email_at, :digest_email_at, :timezone, :photo, :slack_enabled, :github_enabled, days: []])
  end
end

app/controllers/v2/dashboards_controller.rb
module V2
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def index
      @posts = current_user.posts.order("created_at DESC")
      @teams = current_user.teams
    end
    # Add Contextual messages. This will be a place for contextual messages. If the user has logged in for the first time, a message is set accordingly. If the user has not set a status for today, while other team members have put in their statuses; another message. Drive some action from this message.

    def start
    end
  end
end

app/controllers/v2/github_controller.rb
module V2
  class GithubController < ApplicationController
    before_action :authenticate_user!

    def callback
      response = Octokit.exchange_code_for_token(params[:code], ENV['GITHUB_ID'], ENV['GITHUB_SECRET'])
      token = response[:access_token]
      if token.present?
        if team_settings.update(github_token: token, github_enabled: true)
          redirect_to new_v2_github_hook_path
        end
      else
        render text: "Oops! There was a problem."
      end
    end

    private

    def team_id
      session[:team_id]
    end

    def team_settings
      TeamSetting.find_by(team_id: team_id)
    end
  end
end

app/controllers/v2/github_hooks_controller.rb
module V2
  class GithubHooksController < ApplicationController
    before_action :authenticate_token, only: :payload
    before_action :authenticate_user!, except: :payload
    skip_before_action :verify_authenticity_token, only: [:payload]


    def new
      client = Octokit::Client.new access_token: team_settings.github_token
      @repos = client.repos
    end

    def create
      repos = params[:repos]
      CreateGithubHookJob.perform_later(team_id, repos, team_settings)
      redirect_to root_path, notice: "Github Integrated Successfully"
    end

    def edit
      @team = Team.find(params[:id])
      team_settings = TeamSetting.find_by(team_id: params[:id])
      client = Octokit::Client.new access_token: team_settings.github_token
      @repos = client.repos
    end

    def update
      team = Team.find(params[:id])
      repos = params[:repos]
      GithubUpdateJob.perform_later(team, repos, team_settings)
      redirect_to root_path, notice: "Github Repos Configured!"
    end

    def payload
      GithubPayloadJob.perform_later(params)
      render :nothing => true
    end

    def authenticate_token
      hook = GithubHook.where(repo_id: params[:repository][:id], team_id: params[:team_id]).last
      if !token_valid?(hook)
        render :nothing => true, status: :unauthorized
      end
    end

    private

    def team_id
      session[:team_id]
    end

    def team_settings
      TeamSetting.find_by(team_id: team_id)
    end

    def token_valid?(hook)
      digest = OpenSSL::Digest.new('sha1')
      request.headers['X-Hub-Signature']=="sha1=#{OpenSSL::HMAC.hexdigest(digest, hook.token, request.raw_post)}"
    end

  end
end

app/controllers/v2/slack_controller.rb
module V2
  class SlackController < ApplicationController
    before_action :authenticate_user!
    require "slack"

    def callback
      client = Slack::Client.new
      response = client.oauth_access(
        client_id: ENV['SLACK_ID'],
        client_secret: ENV['SLACK_SECRET'],
        code: params[:code],
        redirect_uri: ENV['SLACK_REDIRECT_URI']
      )
      team_settings = TeamSetting.find_by(team_id: session[:team_id])
      if team_settings.update_attributes(
        slack_token: response['access_token'],
        slack_url: response['incoming_webhook']['url'],
        slack_enabled: true
      )
        redirect_to root_path
        flash[:notice] = "Slack successfully integrated"
      else
        render text: "Oops! There was a problem."
      end
    end
  end
end

app/controllers/v2/tags_controller.rb
module V2
  class TagsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_team


    def tasks_list
      if params.values_at(:from_date, :to_date).all?(&:present?)
        tag_tasks = Tag.find_by(name: params[:hash], team_id: @team.id).try(:tasks)
        tasks = tag_tasks.where("DATE(tasks.created_at) BETWEEN ? AND ?", params[:from_date].to_date,
                params[:to_date].to_date) if tag_tasks.present?
      else
        tasks = Tag.where(name: params[:hash], team_id: @team.id).first.try(:tasks)
      end
      @tasks = tasks.paginate(:page => params[:page], :per_page => 10) if tasks.present?
    end

    private

    def set_team
      @team = Team.find(params[:team_id])
    end

  end
end

app/controllers/v2/tasks_controller.rb
module V2
  class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_team, only: [ :new, :hashtasks, :show, :add_my_task,
                                     :prepare_tasks, :complete, :blocker,
                                     :reset, :user_task, :my_task, :team_task
                                   ]
    before_action :find_tasks, only: [:prepare_tasks, :complete, :blocker, :reset]
    def new
      @task = Task.new
    end

    def create
      @task =Task.new(task_params)
      if @task.save
        flash[:notice] = 'Task added successfully'
        redirect_to v2_team_task_path(@task, team_id: @task.team_id)
      else
        render :new
      end
    end

    def hashtasks
      @tasks = Tag.where(name: params[:hash], team_id: @team.id).first.tasks
    end

    def show
      @task  = Task.find(params[:id])
    end

    def prepare_tasks
      @task = Task.new
    end

    def add_my_task
      @task = Task.new(task_params)
      @task.assign_attributes(due_on: set_due_date(task_params), assigned_to: current_user.id)
      if @task.save
        redirect_to prepare_tasks_v2_team_tasks_path
      else
        flash[:alert] = 'Something went wrong.Try again'
        redirect_to prepare_tasks_v2_team_tasks_path
      end
    end

    def complete
      @task = Task.find(params[:id])
      @task.assign_attributes(completed_on: DateTime.now, blocker: false)
      @task.save
      respond_to do |format|
        format.js
      end
    end

    def reset
      @task = Task.find(params[:id])
      @task.completed_on = nil
      @task.save
      respond_to do |format|
        format.js
      end
    end

    def blocker
      @task = Task.find(params[:id])
      @task.blocker = true
      @task.save
      respond_to do |format|
        format.js
      end
    end

    def change_assignee
      @task = Task.find(params[:id])
      @task.assigned_to = params[:assignee_id]
      @task.save
      respond_to do |format|
        format.js
      end
    end

    def user_task
    end

    def my_task
      @users = Team.find(params[:team_id]).users
      @tasks = Task.where(assigned_to: current_user.id, team_id: @team.id).order('created_at DESC').paginate(page: params[:page], per_page: 20)
      respond_to do |format|
        format.js
      end
    end

    def team_task
      @users = Team.find(params[:team_id]).users
      @tasks = Task.includes(:assignee).where(team_id: @team.id).order('created_at DESC').paginate(:page => params[:page], per_page: 20)
      respond_to do |format|
        format.js
      end
    end

    def find_users
      @users = Team.find(params[:team_id]).users.accepted
      respond_to do |format|
        format.js
      end
    end

    def report
      @teams = Team.where(created_by: current_user.id)
      @users = @teams.map{|team| team.users.accepted}.flatten.uniq
      @q = Task.where(team_id: @teams.map { |e| e.id  }).ransack(params[:q])
      @tasks = @q.result.includes(:assignee, :team).paginate(:page => params[:page], per_page: 20)
    end

    private

    def task_params
      params.require(:task).permit(:title, :due_on, :completed_on, :blocker, :team_id, :created_by).merge(created_by: current_user.id)
    end

    def set_team
      @team = Team.find(params[:team_id])
    end

    def set_due_date(task_params)
      if task_params.has_key?(:due_on)
        task_params[:due_on]
      else
        DateTime.now
      end
    end

    def find_tasks
      @task = Task.new
      @tasks_today = Task.where(due_on: Date.today.beginning_of_day..Date.today.end_of_day, assigned_to: current_user.id, team_id: params[:team_id]).order('created_at DESC')
      @tasks_tmw = Task.where(due_on: (Date.today + 1.days).beginning_of_day..(Date.today + 1.days).end_of_day, assigned_to:current_user.id, team_id: params[:team_id]).order('due_on DESC, created_at DESC')
    end

  end
end

app/helpers/teams_helper.rb
module TeamsHelper
  def question_time
    ['2:00 PM', '3.00 PM', '4:00 PM', '5:00 PM', '6:00 PM', '7:00 PM', '8:00 PM', '9:00 PM', '10:00 PM']
  end

  def digest_time
    ['3:00 AM', '4:00 AM', '5:00 AM', '6.00 AM', '7:00 AM', '8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM']
  end

  def team_addition_date(team, user)
    format_date(team.allotment(user).try(:joined_at))
  end

  def team_addition_info(team, user)
    if team.approved?(user)
      "Joined on #{team_addition_date(team, user)}"
    end
  end
end

app/views/v2/teams/_add_member.html.erb
<div class="panel panel-info" >
  <div class="panel-heading">
    <h3>Invite a new member</h3>
  </div>
  <div class='panel-body'>
    <% if current_user.team_admin(@team) %>
      <div class = "row">
        <div class = "col-xs-12 col-sm-12">
          <%= form_tag add_users_v2_team_path(@team) do %>
            <div class="form-group">
              <%= email_field_tag 'email[0]', nil, placeholder: "Email", class: "form-control", required: true %>
            </div>

            <div class="checkbox">
              <label><%= check_box_tag 'observer[0]', 1, false, class: 'role-change' %>Invite as a watcher</label>
            </div>

            <div><div class="form-group"><%= submit_tag 'Invite User', class: "btn btn-success" %></div></div>
          <% end %>
        </div>
      </div>
    <% else %>
      <p>Only team admin can add members.</p>
    <% end %>

  </div>
</div>

app/views/v2/teams/_team_header.html.erb
<%= content_for :page_header do %>
  <div class="row">
    <div class='col-xs-12 col-sm-8'>
      <div class="row">
        <div class='col-xs-12 col-sm-8'>
          <div class="media">
            <h3 class="media-heading">
              <%= @team.name %> <small><span class="label label-info"><%= @team.member_count %> user(s)</span></small>
            </h3>
            <p>
              Question email at <b><%= @team.team_setting.question_email_at%></b><br />
              Digest email at <b><%= @team.team_setting.digest_email_at%></b> (next day)<br/>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="media">
    <div class="row">
      <div class='col-xs-12 col-sm-12'>
        <% if @team.approved?(current_user)%>
          <nav class="navbar navbar-primary">
            <div class="container-fluid">
              <ul class="nav navbar-nav" style="margin-left: -15px">
                <li class="<%= is_active?('v2/tasks', 'prepare_tasks') %>"><%= link_to "Today", prepare_tasks_v2_team_tasks_path(@team) %></li>
                <li class="<%=is_active?('v2/tasks', 'user_task')%>"><%= link_to "Tasks",  user_task_v2_team_tasks_path(@team) %></li>
                <li class="<%=is_active?('v2/teams', 'members')%>"><%= link_to "People", members_v2_team_path(@team)%></li>
                <% if policy(@team).update? %>
                  <li class="<%=is_active?('v2/teams', 'edit')%>"><%= link_to "Settings", edit_v2_team_path(@team) %></li>
                <% end %>
              </ul>
            </div>
          </nav>
        <% else %>
          <p>You are invited to this team.Please accept the request. </b> <%= link_to "Click to Accept", approve_request_v2_team_path(@team), method: :get, :class => "btn btn-success"%></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/v2/teams/edit.html.erb
<%= render 'team_header' %>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3>Team Settings <small>Change your team's details</small></h3>
    <p></p>
  </div>
  <%= form_for @team, { url: v2_team_path(@team) } do |f| %>
    <% if @team.errors.any? %>
      <div id="error_explanation">
        <h4 class="text-danger">
          <%= pluralize(@team.errors.count, "error") %> prohibited
          this team from being saved:
        </h4>
        <ul>
          <% @team.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="panel-body">
      <div class="row">
        <%if current_user.plan.slack? %>
          <% if !@team.team_setting.slack_url.present? %>
            <div class="col-sm-8">
              <h4>Please integrate slack for getting notification in your team's #channel.</h4> </br>
              <a href="https://slack.com/oauth/authorize?&client_id=<%=ENV['SLACK_ID']%>&scope=commands,incoming-webhook,chat:write:bot"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>
            </div><br/>
          <% end %>
        <% end %>

        <%if current_user.plan.github? %>
          <% if !@team.team_setting.github_token.present? %>
            <div class="col-sm-8">
              <h4>Please integrate github for getting commit messages in digest content.</h4> </br>
              <%= link_to github_authorize_url, class: 'btn btn-default' do %>
                <span class="fa fa-github fa-lg" aria-hidden="true"></span>&nbsp;Add To <strong>GitHub</strong>
              <% end%>
            </div>
          <% end %>
        <% end %>

      <div class="col-xs-12 col-sm-8">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :required => true, :placeholder=> "Name of Team",:class => "form-control" %>
        </div>
        <%= f.fields_for :team_setting do |setting| %>
          <div class="form-group">
            <%= setting.label :timezone %>
            <%= setting.time_zone_select :timezone, /Chennai/, {:default => "Chennai"}, {:class => "form-control"} %>
            <p class="help-block">Timezone for the team, based on which the question and the digest emails are sent if any member has not set a timezone.</p>
          </div>

          <% if @team.team_setting.slack_url.present? %>
            <div class="form-group">
              <%= setting.label :slack_enabled, 'Enable Slack Notification' %>&nbsp;&nbsp;
              <%= setting.check_box :slack_enabled, { checked: @team.team_setting.slack_enabled } %>
            </div>
          <% end %>

          <% if @team.team_setting.github_token.present? %>
            <div class="form-group">
              <%= setting.label :github_enabled, 'Enable GitHub Notification' %>&nbsp;&nbsp;
              <%= setting.check_box :github_enabled, { checked: (@team.team_setting.github_enabled), id: "github_enabled" }%>


              <%= link_to "Configure Repos", edit_v2_github_hook_path, class: "btn btn-success btn-sm", id: "config_repos", style: @team.team_setting.github_enabled ? "" : "display:none;" %>
            </div>
          <% end %>

          <div class="form-group">
            <%= setting.label 'Question Email Time' %>
            <%= setting.select :question_email_at, question_time, {}, {:class => "form-control"} %>
            <p class="help-block">The time at which the question email is sent for all team members.</p>
          </div>
          <div class="form-group">
            <%= setting.label 'Digest Email Time' %>
            <%= setting.select :digest_email_at, digest_time, {}, {:class => "form-control"} %>
            <p class="help-block">Time at which a consolidated digest email is sent to all members and watchers.</p>
          </div>
          <div class="form-group">
            <%= setting.label 'Question Email Days/Digest Email Days' %>
            <%=select_tag 'team[team_setting_attributes][days][]', options_for_select(Date::DAYNAMES.zip((0..6).to_a), @team.team_setting.days), multiple: true, class: "form-control render-days", id: "days-select"%>
            <p class="help-block">Question Emails will be sent on these week days only.</p>
          </div>

          <div class="form-group">
            <div class="highlight">
            <label for="exampleInputFile">Change Photo</label>
            <%= setting.file_field :photo, id: 'team-photo' %>
            <p class="help-block">Select a photo to set as the team picture.</p>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-4">
            <button type="submit" class="btn btn-success">Update Details</button>
          </div>
        </div>
        <br /><br />
        <div class="row">
          <div class="col-xs-12 col-sm-12">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <h3 class="panel-title">Don't want this team anymore?</h3>
              </div>
              <div class="panel-body">
                <p>When you delete a team, you lose all the associated data and settings with it.</p>
                <p><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal"><i class="fa fa-trash"></i> Delete Team</button></p>
              </div>
            </div>
          </div>
          <p style="margin-bottom: 20px;">&nbsp;</p>
        </div>

      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="highlight">
          <span class="label label-info">STEP 1</span>
          <h4>All team members will receive a daily question email at <%= @team.question_email_at%> to update daily tasks</h4>
          <p>Members need to update their tasks and status.</p>
        </div>

        <div class="highlight">
          <span class="label label-info">STEP 2</span>
          <h4>Consolidated digest email</h4>
          <p>At <%= @team.digest_email_at%> the next day, a digest email will be sent to all team members from AgileJoker.</p>
        </div>

      </div>
      </div>
    </div>
  <% end %>
</div>


<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><b>Delete Team?</b></h4>
      </div>
      <div class="modal-body form-group">
        <p>This action <strong>CANNOT</strong> be undone. This will permanently delete your  Team <strong><%= @team.name%></strong>, posts and remove all related data.<br/>
          Please type the name of your team to confirm</p>
        <%= text_field_tag :team_name, "", class: "form-control", data: {name: @team.name}, id: "txtConfirmName", onChange: "checkNameMatch();"%>
      </div>
      <div class="modal-footer">
        <div>
          <%= link_to 'Delete this team','#', class: "btn btn-block btn-danger", id:'button', disabled: true, data:{url: disable_v2_team_path} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/v2/teams/index.html.erb
<%if @teams.present?%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><strong> Your Teams <span class="glyphicon glyphicon-chevron-down"></span></strong></h2>
  </div>
<table class="table table-responsive table-bordered">
  <tr>
    <th>Team Name</th>
    <th>Details </th>
    <th></th>
    <th>Accepted?</th>
    <th></th>
  </tr>
  <% @teams.each do |team| %>
    <tr>
      <td><%= team.name %><%= image_tag team.team_setting.photo.medium.url, class: "img-thumbnail",:size => '150x100' %></td>
      <td><%= link_to "Team Details", team_path(team), method: :get%></td>
      <% if team.approved?(current_user)%>
        <td><%= link_to "Team History", team_history_team_path(team)%></td>
        <td>Accepted</td>
        <td><button type="button" class="btn btn-info btn-small" data-toggle="modal" data-target="#myModal<%= team.id%>">Team Settings  <span class= "glyphicon glyphicon-resize-full"></span></button>
            <!-- Modal -->
            <div id="myModal<%=team.id%>" class="modal fade" role="dialog">
              <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Team Settings</h4>
                  </div>
                  <div class="modal-body">
                    <p>Question Email Time : <b><%= team.team_setting.question_email_at%></b></p>
                    <p>Digest Email Time : <b><%= team.team_setting.digest_email_at%></b>(next day)</p>
                    <p>Timezone : <b><%= team.team_setting.timezone%></b></p>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>

              </div>
            </div>
        </td>
      <% else %>
        <td></td>
        <td>Pending Acceptance <%= link_to "Click to Accept", approve_request_team_path(team), method: :get, :class => "btn btn-success"%></td>
      <% end %>
    </tr>
  <%end%>
</table>
</div>
<% else %>
  <div class="well"> Hey !! You don't have any teams yet.Try creating new one <%= link_to('Create Team', new_team_path, method: :get,  :class => "btn btn-success") %></div>
<% end %>

app/views/v2/teams/show.html.erb
<% title "#{@team.try(:name)} | AgileJoker" %>
<%= render 'team_header' %>