config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, :controllers => { :confirmations => "confirmations", registrations: 'registrations'  }
  root 'v2/dashboards#index'
  get :start, to: 'dashboards#start'

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  mount_griddler
  resources :plans, only: [:index] do
    collection do
      get 'upgrade'
    end
  end
  resources :teams, except: [:index] do
    member do
      post 'add_users'
      get 'approve_request'
      get 'activity'
      post 'role_change'
      get 'members'
      get 'resend_invitation'
      post 'remove_user'
      get 'disable'
    end
  end

  get '/slack/callback', to: 'slack#callback'
  get '/github/callback', to: 'github#callback'

  resources :github_hooks, only: [:new, :create, :edit, :update] do
    collection do
      post '/teams/:team_id/payload', to: 'github_hooks#payload'
    end
  end

  resource :user, only: [:show, :edit, :update]

  resources :posts, only: [:index, :new, :create, :edit, :update] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end

  resources :instant_posts do
    collection do
      get 'instant_updates'
      post 'save_updates'
    end
  end
  resources :reports, only: [:index]

  # Super Admin dashboard
  namespace :admin, path: 'captains', as: 'captains' do
    resource :dashboard, only: [], path: "deck", as: 'deck' do
      member do
        get 'full'
        get 'today'
      end
    end
  end

  namespace :v2 do
    resources :teams, except: [:index] do
      member do
        post 'add_users'
        get 'approve_request'
        get 'activity'
        post 'role_change'
        get 'members'
        get 'resend_invitation'
        post 'remove_user'
        get 'disable'
      end
      resources :tasks do
        member do
          put 'complete'
          put 'reset'
          put 'blocker'
          put 'change_assignee'
        end
        collection do
          get 'prepare_tasks'
          post 'add_my_task'
          get 'user_task'
          get 'my_task'
          get 'team_task'
        end
      end

      resources :tags, only: [:show] do
        collection do
          get 'tasks_list'
        end
      end
    end

    resources :tasks, only: [:index] do
      collection do
        get 'report'
        get 'find_users'
      end
    end
    get '/slack/callback', to: 'slack#callback'
    get '/github/callback', to: 'github#callback'

    resources :github_hooks, only: [:new, :create, :edit, :update] do
      collection do
        post '/teams/:team_id/payload', to: 'github_hooks#payload'
      end
    end

    resources :dashboards, only: [:index]
  end

  resources :orders, only: [:new, :create] do
    member do
      get 'success'
      get 'error'
    end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def today
      from_date = Date.current.beginning_of_day
      to_date = 1.day.from_now.end_of_day

      @metrics = metrics(from_date, to_date)
      set_allotments(from_date, to_date)
      authorize :super_admin, :index?
    end

    def full
      from_date = 90.days.ago.beginning_of_day
      to_date = 1.day.from_now.end_of_day

      @metrics = metrics(from_date, to_date)
      set_allotments(from_date, to_date)
      authorize :super_admin, :index?
    end

    private

    def metrics(from_date, to_date)
      signups = User.spanning(from_date, to_date)
      teams = Team.spanning(from_date, to_date)
      pending_users = User.spanning(from_date, to_date).where(status: false)
      subscriptions = User.spanning(from_date, to_date).joins(:subscriptions).group("subscriptions.plan_code").count
      plans = Hash[*Plan.pluck(:code, :name).flatten]

      {
        signups: signups.length,
        pending_users: pending_users.length,
        teams: teams.length,
        subscriptions: subscriptions,
        plans: plans
      }
    end

    def set_allotments(from_date, to_date)
      @q = Allotment
            .spanning(from_date, to_date)
            .includes(:team, :user)
            .order(:user_id, :team_id)
            .ransack(params[:q])

      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @allotments = @q.result.includes(:team, :user).paginate(:page => params[:page])
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("created_at DESC")
    @teams = current_user.teams
  end
  # Add Contextual messages. This will be a place for contextual messages. If the user has logged in for the first time, a message is set accordingly. If the user has not set a status for today, while other team members have put in their statuses; another message. Drive some action from this message.

  def start
  end
end

app/controllers/v2/dashboards_controller.rb
module V2
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def index
      @posts = current_user.posts.order("created_at DESC")
      @teams = current_user.teams
    end
    # Add Contextual messages. This will be a place for contextual messages. If the user has logged in for the first time, a message is set accordingly. If the user has not set a status for today, while other team members have put in their statuses; another message. Drive some action from this message.

    def start
    end
  end
end

app/views/dashboards/index.html.erb
<% title "Dashboard | AgileJoker" %>
<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-12 col-sm-8'>
      <div class="media headerphoto-wrap">
        <div class="media-left">
          <%=image_tag current_user.photo.medium.url, class: 'img-circle img-responsive headerphoto' %>
        </div>
        <div class="media-body">
          <h3 class="media-heading">Hello, <%= current_user.try(:name)%></h3>
          <p>
            Welcome to AgileJoker!<br />Start viewing your team's updates directly in your inbox.
          </p>
        </div>
      </div>
    </div>
    <div class='col-xs-12 col-sm-4'>
      <%= render 'shared/feedback' %>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h3> My Teams<small class='sr-only'> All teams, which you are part of</small></h3>
    </div>
    <div class='col-xs-4 col-sm-4'>
      <div class="pull-right">
        <h3>
          <%= link_to new_team_path, class: 'btn btn-success' do %>
            <span class="glyphicon glyphicon-plus-sign"></span> Create a New Team
          <% end %>

        </h3>
      </div>
    </div>
  </div>
<% end %>
<% if @teams.empty? %>
  <div class="media headerphoto-wrap">
        <div class="media-left">
          <%=image_tag 'joker.jpg', class: 'img-responsive headerphoto' %>
        </div>
        <div class="media-body">
          <h3 class="media-heading text-warning">Oops! You just got the Joker!</h3>
          <p>
            You are not part of any team.
            <br /><br />
          </p>
          <p>
            No worries! Click on <%= link_to 'Create a New Team', new_team_path, class: 'label label-success text-normal' %> to create your first team.<br />You can invite your folks after creating the team.
          </p>
        </div>
      </div>
<% else %>
  <div class="row">
    <% @teams.each do |team| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <div class="team-rect-wrap">
            <%= link_to team_path(team) do %>
              <%= image_tag team.team_setting.photo.medium.url, style: 'width: 100%; display: block;' %>
            <% end %>
          </div>
          <div class="caption">
            <%= link_to team_path(team) do %>
              <h3><%= team.name %></h3>
            <% end %>
            <p><%= team.users.accepted.count%> Team member(s)</p>
            <% if !team.approved?(current_user)%>
              <div>
                <p><%= link_to approve_request_team_path(team), method: :get, class: "btn btn-success btn-xs btn-block" do %>
                  <span class="glyphicon glyphicon-envelope"></span> Click to accept invite
                  <% end %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/dashboards/start.html.erb
<% title "Dashboard | AgileJoker" %>
<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-12 col-sm-12'>
      <div class="media headerphoto-wrap">
        <div class="media-left">
          <%=image_tag current_user.photo.medium.url, class: 'img-circle img-responsive headerphoto' %>
        </div>
        <div class="media-body">
          <h3 class="media-heading">Hello, <%= current_user.try(:name)%></h3>
          <p>
            Welcome to AgileJoker!<br />Start viewing your team's updates directly in your inbox.
          </p>
        </div>
      </div>
    </div>
    <div class='col-xs-12 col-sm-12'>
      <%= render 'shared/how_it_works' %>
    </div>
  </div>
<% end %>