config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, :controllers => { :confirmations => "confirmations", registrations: 'registrations'  }
  root 'v2/dashboards#index'
  get :start, to: 'dashboards#start'

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  mount_griddler
  resources :plans, only: [:index] do
    collection do
      get 'upgrade'
    end
  end
  resources :teams, except: [:index] do
    member do
      post 'add_users'
      get 'approve_request'
      get 'activity'
      post 'role_change'
      get 'members'
      get 'resend_invitation'
      post 'remove_user'
      get 'disable'
    end
  end

  get '/slack/callback', to: 'slack#callback'
  get '/github/callback', to: 'github#callback'

  resources :github_hooks, only: [:new, :create, :edit, :update] do
    collection do
      post '/teams/:team_id/payload', to: 'github_hooks#payload'
    end
  end

  resource :user, only: [:show, :edit, :update]

  resources :posts, only: [:index, :new, :create, :edit, :update] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end

  resources :instant_posts do
    collection do
      get 'instant_updates'
      post 'save_updates'
    end
  end
  resources :reports, only: [:index]

  # Super Admin dashboard
  namespace :admin, path: 'captains', as: 'captains' do
    resource :dashboard, only: [], path: "deck", as: 'deck' do
      member do
        get 'full'
        get 'today'
      end
    end
  end

  namespace :v2 do
    resources :teams, except: [:index] do
      member do
        post 'add_users'
        get 'approve_request'
        get 'activity'
        post 'role_change'
        get 'members'
        get 'resend_invitation'
        post 'remove_user'
        get 'disable'
      end
      resources :tasks do
        member do
          put 'complete'
          put 'reset'
          put 'blocker'
          put 'change_assignee'
        end
        collection do
          get 'prepare_tasks'
          post 'add_my_task'
          get 'user_task'
          get 'my_task'
          get 'team_task'
        end
      end

      resources :tags, only: [:show] do
        collection do
          get 'tasks_list'
        end
      end
    end

    resources :tasks, only: [:index] do
      collection do
        get 'report'
        get 'find_users'
      end
    end
    get '/slack/callback', to: 'slack#callback'
    get '/github/callback', to: 'github#callback'

    resources :github_hooks, only: [:new, :create, :edit, :update] do
      collection do
        post '/teams/:team_id/payload', to: 'github_hooks#payload'
      end
    end

    resources :dashboards, only: [:index]
  end

  resources :orders, only: [:new, :create] do
    member do
      get 'success'
      get 'error'
    end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def today
      from_date = Date.current.beginning_of_day
      to_date = 1.day.from_now.end_of_day

      @metrics = metrics(from_date, to_date)
      set_allotments(from_date, to_date)
      authorize :super_admin, :index?
    end

    def full
      from_date = 90.days.ago.beginning_of_day
      to_date = 1.day.from_now.end_of_day

      @metrics = metrics(from_date, to_date)
      set_allotments(from_date, to_date)
      authorize :super_admin, :index?
    end

    private

    def metrics(from_date, to_date)
      signups = User.spanning(from_date, to_date)
      teams = Team.spanning(from_date, to_date)
      pending_users = User.spanning(from_date, to_date).where(status: false)
      subscriptions = User.spanning(from_date, to_date).joins(:subscriptions).group("subscriptions.plan_code").count
      plans = Hash[*Plan.pluck(:code, :name).flatten]

      {
        signups: signups.length,
        pending_users: pending_users.length,
        teams: teams.length,
        subscriptions: subscriptions,
        plans: plans
      }
    end

    def set_allotments(from_date, to_date)
      @q = Allotment
            .spanning(from_date, to_date)
            .includes(:team, :user)
            .order(:user_id, :team_id)
            .ransack(params[:q])

      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @allotments = @q.result.includes(:team, :user).paginate(:page => params[:page])
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("created_at DESC")
    @teams = current_user.teams
  end
  # Add Contextual messages. This will be a place for contextual messages. If the user has logged in for the first time, a message is set accordingly. If the user has not set a status for today, while other team members have put in their statuses; another message. Drive some action from this message.

  def start
  end
end

app/controllers/v2/dashboards_controller.rb
module V2
  class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def index
      @posts = current_user.posts.order("created_at DESC")
      @teams = current_user.teams
    end
    # Add Contextual messages. This will be a place for contextual messages. If the user has logged in for the first time, a message is set accordingly. If the user has not set a status for today, while other team members have put in their statuses; another message. Drive some action from this message.

    def start
    end
  end
end

app/views/admin/dashboards/_metrics.html.erb
<div class = "row">
  <div class="col-sm-4 col-xs-12">
    <div class="panel panel-success">
      <div class="panel-body">
        <div class = "row">
          <div class="col-sm-4">
            <i class="fa fa-handshake-o fa-4x" aria-hidden="true"></i>
          </div>
          <div class="col-sm-8">
            <h4><%= @metrics[:signups]%> Signups</h4>
            <h4><%= @metrics[:pending_users]%> Un-confirmed</h4>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="panel panel-success">
      <div class="panel-body">
        <div class = "row">
          <div class="col-sm-4">
            <i class="fa fa-users fa-4x" aria-hidden="true"></i>
          </div>
          <div class="col-sm-8">
            <h4><%= @metrics[:teams]%> Teams</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="panel panel-success">
      <div class="panel-body">
        <div class = "row">
          <div class="col-sm-4">
            <i class="fa fa-money fa-4x" aria-hidden="true"></i>
          </div>
          <div class="col-sm-8">
            <% if @metrics[:subscriptions].present? %>
              <% @metrics[:subscriptions].each do |plan_code, subscriptions| %>
                <h4><b><%= @metrics[:plans][plan_code.to_i] %></b> (<%= subscriptions %> users)</h4>
              <% end %>
            <% else %>
              <h4>0 Subscriptions</h4>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/dashboards/_user_list.html.erb
<div class="row mrg-btm">
  <div class="col-md-4 col-xs-6">
    <div class="page_info text-muted">
      <%= page_entries_info @allotments %>
    </div>
  </div>
  <div class="col-md-6">
  </div>
  <div class="col-md-2 col-xs-6">
    <div class="pull-right">
      <%= link_to '#' do %>
        <i class="fa fa-file-text-o" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-hover table-bordered ta-bg-color">
    <tr>
      <th><%= sort_link @q, :user, "User" %></th>
      <th>User Email</th>
      <th>Team</th>
      <th>Joined</th>
      <th>TZ</th>
      <th>Conf?</th>
      <th>LoginAt</th>
      <th>UID</th>
      <th>TID</th>
    </tr>
  <% @allotments.each do |allotment| %>
    <tr>
      <td><%= allotment.user.name  %></td>
      <td><%= allotment.user.email  %></td>
      <td><%= allotment.team.name  %></td>
      <td><%= allotment.user.created_at %></td>
      <td><%= allotment.user.timezone %></td>
      <td><%= allotment.user.status %></td>
      <td><%= allotment.user.last_sign_in_at %></td>
      <td><%= allotment.user.id %></td>
      <td><%= allotment.team.id %></td>
    </tr>
  <% end %>
    <tr>
      <td colspan="4">
        <div class="flickr_pagination">
          <%= will_paginate @allotments, :container => false %>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/admin/dashboards/full.html.erb
<% title "Captain's Deck | AgileJoker" %>

<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h3>Admin Dashboard <small>View statistics of agilejoker</small></h3>
    </div>
  </div>
  <div class="media">
    <div class="row">
      <div class='col-xs-12 col-sm-12'>
        <ul class="nav nav-tabs">
          <li role="presentation"><%=link_to 'Today', today_captains_deck_path, :'data-target' => "#today" %></li>
          <li role="presentation" class="active"><%=link_to 'All-Time', full_captains_deck_path, :'data-target' => "#full" %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>


<div class="tab-content">
  <div id="today" data-target="#today" class="tab-pane"></div>
  <div id="full" data-target="#full" class="tab-pane"></div>
</div>


<div id="today" class="tab-pane"></div>

<div id="full" class="tab-pane active">
  <%= render 'metrics' %>
  <%= render 'user_list' %>
</div>

app/views/admin/dashboards/today.html.erb
<% title "Captain's Deck | AgileJoker" %>

<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h3>Admin Dashboard <small>View statistics of agilejoker</small></h3>
    </div>
  </div>
  <div class="media">
    <div class="row">
      <div class='col-xs-12 col-sm-12'>
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><%=link_to 'Today', today_captains_deck_path, :'data-target' => "#today" %></li>
          <li role="presentation"><%=link_to 'All-Time', full_captains_deck_path, :'data-target' => "#full" %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>


<div class="tab-content">
  <div id="today" data-target="#today" class="tab-pane"></div>
  <div id="full" data-target="#full" class="tab-pane"></div>
</div>


<div id="today" class="tab-pane active">
  <%= render 'metrics' %>
  <%= render 'user_list' %>
</div>

<div id="full" class="tab-pane"></div>