config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, :controllers => { :confirmations => "confirmations", registrations: 'registrations'  }
  root 'v2/dashboards#index'
  get :start, to: 'dashboards#start'

  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  mount_griddler
  resources :plans, only: [:index] do
    collection do
      get 'upgrade'
    end
  end
  resources :teams, except: [:index] do
    member do
      post 'add_users'
      get 'approve_request'
      get 'activity'
      post 'role_change'
      get 'members'
      get 'resend_invitation'
      post 'remove_user'
      get 'disable'
    end
  end

  get '/slack/callback', to: 'slack#callback'
  get '/github/callback', to: 'github#callback'

  resources :github_hooks, only: [:new, :create, :edit, :update] do
    collection do
      post '/teams/:team_id/payload', to: 'github_hooks#payload'
    end
  end

  resource :user, only: [:show, :edit, :update]

  resources :posts, only: [:index, :new, :create, :edit, :update] do
    collection do
      match 'search' => 'posts#search', via: [:get, :post], as: :search
    end
  end

  resources :instant_posts do
    collection do
      get 'instant_updates'
      post 'save_updates'
    end
  end
  resources :reports, only: [:index]

  # Super Admin dashboard
  namespace :admin, path: 'captains', as: 'captains' do
    resource :dashboard, only: [], path: "deck", as: 'deck' do
      member do
        get 'full'
        get 'today'
      end
    end
  end

  namespace :v2 do
    resources :teams, except: [:index] do
      member do
        post 'add_users'
        get 'approve_request'
        get 'activity'
        post 'role_change'
        get 'members'
        get 'resend_invitation'
        post 'remove_user'
        get 'disable'
      end
      resources :tasks do
        member do
          put 'complete'
          put 'reset'
          put 'blocker'
          put 'change_assignee'
        end
        collection do
          get 'prepare_tasks'
          post 'add_my_task'
          get 'user_task'
          get 'my_task'
          get 'team_task'
        end
      end

      resources :tags, only: [:show] do
        collection do
          get 'tasks_list'
        end
      end
    end

    resources :tasks, only: [:index] do
      collection do
        get 'report'
        get 'find_users'
      end
    end
    get '/slack/callback', to: 'slack#callback'
    get '/github/callback', to: 'github#callback'

    resources :github_hooks, only: [:new, :create, :edit, :update] do
      collection do
        post '/teams/:team_id/payload', to: 'github_hooks#payload'
      end
    end

    resources :dashboards, only: [:index]
  end

  resources :orders, only: [:new, :create] do
    member do
      get 'success'
      get 'error'
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!

  def upgrade
    SuperAdminMailer.upgrade_interest(current_user, params[:plan_id]).deliver_now
  end

  def index
  end
end

app/views/plans/index.html.erb
<% title "List of available plans | AgileJoker" %>
<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h3>Upgrade <small>Choose a plan that suits your need</small></h3>
    </div>
  </div>
<% end %>

<div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h4>Current Plan  : <span class="label label-success"><%= current_user.plan.name%></span></h4>
      <br />
    </div>
</div>

<div class="row">
  <div class="col-sm-6 col-md-6">
            <div class="card">
              <div class="card-title bg-success">
                <h3>Team Joker <span class="label label-success">PRO</span></h3>
              </div>
              <div class="card-content">
                <p></p>
                <ul>
                  <li>Upto 20 teams</li>
                  <li>Upto 20 users/team</li>
                  <li>No Data limits</li>
                  <li>Reports, Scheduled report emails</li>
                  <li>E-mail Support</li>
                </ul>
                <p>Upgrade to this plan for managing multiple teams effectively.</p>
                <hr>
                <h3>$9 / month <small>(paid month to month)</small></h3>
                <hr>
                <p><a class="btn btn-danger btn-lg btn-block" href="<%= new_order_path(plan_id: Plan.where(code: 112).first.id) %>">Upgrade</a></p>
              </div>
            </div>
            </div>
            <div class="col-sm-6 col-md-6">
            <div class="card">
              <div class="card-title bg-info">
                <h3>Custom Joker <span class="label label-default">ENTERPRISE</span></h3>
              </div>
              <div class="card-content">
                <p></p>
                <ul>
                  <li>More than 20 teams</li>
                  <li>All premium features</li>
                  <li>Feature customizations</li>
                  <li>E-mail Support</li>
                </ul>
                <p>Contact us at <a href='mailto:support@agilejoker.com'>support@agilejoker.com</a> </p>
                <hr>
                <h3>Talk to us for price</h3>
                <hr>
                <p><a class="btn btn-default btn-lg btn-block" href="<%= upgrade_plans_path(plan_id: 2) %>">Talk to Us</a></p>
              </div>
            </div>
  </div>
  </div>

app/views/plans/upgrade.html.erb
<% title "Plan upgrade | AgileJoker" %>
<% content_for :page_header do %>
  <div class="row">
    <div class='col-xs-8 col-sm-8'>
      <h3>Upgrade your plan  <small></small></h3>
    </div>
  </div>
<% end %>
<div class="highlight">
<div class="row">
    <div class='col-xs-12 col-sm-12'>

      <div class='media'>
        <div class='media-content'>
          <h2>Thank you. Your rock!</h2>

          <p>Thanks for your interest!</p>
          <p>We are in the process of rolling out the premium features.<br />We will get back to you as soon as possible. </p>
          <p>In case of any questions send us an email at <a href='mailto:support@agilejoker.com'>support@agilejoker.com</a>.</p>
        </div>
      </div>
      <br />
      <br />
    </div>
</div>
</div>